### ISSUE TITLE
Deploy a `mongo` db to the Auth Service

### ISSUE THREAD

**Issue by rodriggj** [rodriggj/ticketing_app#30]

**Comment by rodriggj** [comment]
1. Nav to the `ticketing-app / auth` directory 
2. Install mongoose with 
```s
npm i mongoose --save
```

**Comment by rodriggj** [comment]
Create a mongodb `Deployment` in K8

1. Nav to `tickting-app / auth / infra / k8s` and create a file called `auth-mongo-depl.yml`
2. In that file enter the following config: 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-mongo-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: auth-mongo
  template:
    metadata:
      labels: 
        app: auth-mongo
    spec: 
      containers: 
        - name: auth-mongo
          image: mongo
```

**Comment by rodriggj** [comment]
We also need to create an `ClusterIP` so we can speak to the mongo-db. To do this simply add to the existing `auth-mongo-depl.yaml` file the following `Service` manifest: 

```yaml
...
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-mongo-srv
spec: 
  selector: 
    app: auth-mongo
  ports: 
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
```
