### ISSUE TITLE
Implement Signing Key as a Secret in K8

### ISSUE THREAD

**Issue by rodriggj** [rodriggj/ticketing_app#44]
When we use JWT to create our Authentication Token we will need to pass the `signing key` to each service that is using the JWT token in order to decode the JWT token. The `signing key` if exposed can give access to unwanted users of our services. To store an item that must be secure K8 provides a `Secret` Object. We need to implement `Secret` across our K8 cluster.

**Comment by rodriggj** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/8760590/162635136-61d5d69c-0e19-4559-9bf1-68fde9b194db.png">

**Comment by rodriggj** [comment]
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/8760590/162635443-b6c54fcc-2cf6-48fc-99d1-dea95ebef00e.png">

**Comment by rodriggj** [comment]
For dev env 
```s
kubectl create secret generic jwt-secret --from-literal=JWT_KEY=gtkca4evr
```

**Comment by rodriggj** [comment]
To access the key with the respective Pods across our microservices, we need to configure our `auth-depl.yaml` file to make use of the secret. 

Modify your `auth-depl.yaml` file as follows: 

```yaml 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: auth
  template: 
    metadata: 
      labels: 
        app: auth
    spec: 
      containers: 
        - name: auth
          image: us.gcr.io/ticketing-dev-345513/auth
          env: 
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-srv
spec: 
  selector: 
    app: auth
  ports: 
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
```
